### ISSUE TITLE
No profile for team 'x' matching 'x' Xcode couldn't find any provisioning profiles matching

### ISSUE THREAD

**Issue by Wumbaloo** [sparkfabrik/ios-build-action#11]
Hello,

I try to use your new version (2.0.0) since it has been released but I can't make match work.

Here's my stacktrace:
```
[21:13:00]: ▸ error: No profile for team 'TEAM_ID' matching 'MyProfile' found: Xcode couldn't find any provisioning profiles matching 'TEAM_ID/MyProfile'. Install the profile (by dragging and dropping it onto Xcode's dock item) or select a different one in the Signing & Capabilities tab of the target editor. (in target 'App' from project 'App')
```

I double / triple check and the profile MyProfile with the TEAM_ID does exists in the [Certificates, Identifiers & Profiles](https://developer.apple.com/account/resources/profiles/list) list.
It's not revoked and it is valid.

-----------
### **EDIT:**

Fixed, the issue has been fixed by changing the code signing identity and the provisioning profile to correct ones and by using a mystic thing where you add "App Groups" & "Keychain Sharing" to Capabilities and then you delete them.

**Comment by edodusi** [comment]
@Wumbaloo do you think something can be improved on the code base of the action and/or the docs?
I tested it only on my apps and they have more or less the same strutture.

**Comment by Wumbaloo** [comment]
Why not, as developer I prefer to have a lot of documentation, even if this is not necessary, **just in case**.

What I understand and how I make it works is that I made the GitHub pipeline generate the certificate, then I download it through [Apple Website](https://developer.apple.com/account/resources/certificates/list) and set it to Xcode to make it available for the pipeline.

Also, I had some problems with `increment-build-number`, the error was `No value found for app_identifier` for the step `latest_testflight_build_number` and I had to add `IOS_APP_ID` environment variable in my pipeline. (along with `TEAM_NAME` and `PROJECT_PATH` but I don't know if it worked without them)

So it looks like this:
```yml

      - uses: sparkfabrik/ios-build-action@v2.0.0
        env:
          PROJECT_PATH: dist/ios-app/App/App.xcodeproj
          IOS_APP_ID: app.X.my
          TEAM_NAME: "X"
        with:
          ...
```
