### ISSUE TITLE
APP_ID does not exist in environment variables

### ISSUE THREAD

**Issue by deivyrene** [sparkfabrik/ios-build-action#21]
The following variable does not exist when assigning the parameters to the environment variables `index.js`

```ruby
# fastlane/Matchfile

app_identifier(ENV["APP_ID"])
```

Is it intentional?

**Comment by edodusi** [comment]
@abarnto I think this could be a leftover and maybe the correct value should be `IOS_APP_ID`, what do you think?

**Comment by abarnto** [comment]
I agree @edodusi. I've just opened the PR with the fix. Thanks for pointing that out @deivyrene.

**Comment by edodusi** [comment]
Merged. Thanks
