### ISSUE TITLE
Setting up github action

### ISSUE THREAD

**Issue by Richie911** [sparkfabrik/ios-build-action#28]
Hello,
I am trying to use this github action to create a CI/CD pipeline for an Ionic angular project and some of the required keys are not self explanatory so if anyone is available to give me some insight on them that will be much appreciated

**Comment by giuliobracci** [comment]
Hi @Richie911, could you specify which keys you have doubts about? Have you read the [README](https://github.com/sparkfabrik/ios-build-action/blob/master/README.md)? There you can find a brief description for each variable needed to set up the GitHub action

**Comment by Richie911** [comment]
The Apple-key-content, I want to know the steps to retrieve that from the Apple developer account. Also, could you explain what the match git credentials are all about?

**Comment by giuliobracci** [comment]
@Richie911 I'm leaving some documentation for you that might help you setup the Github Action!

[Here](https://docs.fastlane.tools/app-store-connect-api/) you have a description on how to retrive the needed API key to connect with the App Store API. 
And [here's](https://docs.fastlane.tools/actions/match/) more informations about the git credentials. There's a very clear step by step guide on Fastlane's documentation of how to store the certificates and use the git basic auth

**Comment by Richie911** [comment]
Sure, Thank you @giuliobracci

**Comment by giuliobracci** [comment]
@Richie911 you're welcome, I added a few more links in the README with also examples from Fastlane's documentation, so it will be clearer for future developers
