### ISSUE TITLE
No value for APP_IDENTIFIER

### ISSUE THREAD

**Issue by Richie911** [sparkfabrik/ios-build-action#30]
I am having this issue of app_identifier not found and I want to know if I missed something or I am providing the wrong ios-app-id.
So can someone share light on this error that I am facing. Also is the ios-app-id the team_id.bundleId or the Apple ID. I will like to know that as well

![image](https://github.com/sparkfabrik/ios-build-action/assets/56179749/c7406b6d-e265-4318-9189-e01988532628)

**Comment by Richie911** [comment]
@paolomainardi @stefanomainardi @marcogiacomassi @osvaldot

**Comment by edodusi** [comment]
@Richie911 if you think this is a good way to ask for help in Open Source, let me tell you that you have it all wrong.

**Comment by onmotion** [comment]
@Richie911 try to use `sparkfabrik/ios-build-action@v2.3.2`

**Comment by Richie911** [comment]
@edodusi 
Sorry about that

**Comment by Richie911** [comment]
@onmotion
I am using that version

**Comment by Richie911** [comment]
The solution was putting the ios-app-id in quotes

**Comment by edodusi** [comment]
@Richie911 thanks for posting the solution, that's a good practice. Sorry if I was a bit rude with my comment but I think we need to make this platform a better place for maintainers, thanks for understanding.

**Comment by Richie911** [comment]
@edodusi I totally understand. Thanks for your assistance
